title: "One More Byte"
author: "Peter Hendriks"
description: "Personal stories about software development."
#subheading: "Personal stories about software development"
more: "read more"
url: "http://peterhendriks.github.io"
# baseurl: "/contrast" # comment out if in root directory

comments:
    disqus: "peterhendriks"
#    isso: "comments.mysite.org"

style:
    body: "whitesmoke"
    padding: 33%
    anchor: "#46f"
    serif-heading: true
    nav: "#181818"
#    headline: "#06f"
    description: "white"
    article:
        odd: "#ffffff"
        even: "#222222"

links:
  - github: "https://github.com/peterhendriks"
  - twitter: "https://twitter.com/PeterHendriks80"
  - google-plus: "https://plus.google.com/+PeterHendriks"
  - web: "http://www.22flows.nl"

excerpt_separator: "\n\n\n"
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
